on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'           # Push events to every tag not containing /
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - run: cargo fmt --check
      - run: cargo test
      - uses: katyo/publish-crates@v2
        with:
            registry-token: ${{ secrets.CRATES_TOKEN }}